Add/license url override
sensslen/nuget-license pull request #102
Opened 2024-11-07 13:58 UTC by pymenguy

Hello,

When testing the capabilities of the tool, I noticed the URL could not be overridden by the option "override-package-information". 

For many reasons URLs may be broken (domain name changing/expiring, changing SCM provider, etc). If we were to attempt the download of the original license, it would fail. 

One such package I encountered is [SharpDX](https://www.nuget.org/packages/SharpDX), which still has the invalid URL linked on nuget.org : 
* Invalid: http://sharpdx.org/License.txt
* Still active: https://github.com/sharpdx/SharpDX/blob/v4.2.0/License.txt

Following what was written in #53 and #68 I also added the LicenceUrl to the list of fields and to the tests.

2024-11-07 15:46 UTC, sensslen commented
Thank you very much for your contribution. Would you mind adding a test that actually verifies that the LicenseUrl actually ends up in the override package information?

2024-11-07 15:46 UTC, sensslen requested changes
Thank you very much for your contribution. Would you mind adding a test that actually verifies that the LicenseUrl actually ends up in the override package information?

2025-01-28 01:40 UTC, paulbuechner commented
Hey,

Could this feature please be added? I also encountered a use case where I needed to override the URL, too.

If the original PR contributor is not willing to finish it, I suggest you add the test yourself afterward (if it is only the test that is missing).

@pymenguy @sensslen 

Appreciate your work on this tool! Keep it coming.

2025-02-03 06:36 UTC, merged

2025-02-03 09:38 UTC, sensslen commented
@paulbuechner @pymenguy this feature has now been merged to main. It has not made it's way to a release. I'm bundling this with slnx support