Add an ignored columns option
sensslen/nuget-license pull request #103
Opened 2024-11-07 14:31 UTC by pymenguy

In the table output, there are many columns which clutter the output and reduce readability.

This command-line option offer the possibility to the user to remove undesirable columns, using the same format as the `ignored-packages` option.  

Existing tests are still passing, however I am unsure how to add new cases as the output formatter is created only once at the setup phase. 

Maybe a second `CreateUut` function with the ignored columns builtin, (and the same validations files for Json output, as it is not affected) or specific test functions in the `TableOutputFormatterTest.cs` instead of `TestBase.cs`

2024-11-07 15:43 UTC, sensslen commented
I'd really love to see this feature unit tested as well. Also I'm not sure it's wise to only implement this feature in the tabular output only. Also I'm not a big fan of using magic strings here. Would it be feasible to create an enum or something similar (a source generator would be an ideal fit for this) to make sure only the information available can be specified for exclusion.....

2024-11-07 15:46 UTC, sensslen requested changes
I'd really love to see this feature unit tested as well. Also I'm not sure it's wise to only implement this feature in the tabular output only. Also I'm not a big fan of using magic strings here. Would it be feasible to create an enum or something similar (a source generator would be an ideal fit for this) to make sure only the information available can be specified for exclusion.....

2024-11-08 18:09 UTC, pymenguy commented
I added an enum to match columns name to a common descriptor, and a proof of concept for the Json output. 

Also, I've added tests results when removing columns, I didn't had the time to make it for all options in the enumeration.
A separate test case is written for the case where all columns are removed, which would crash the TablePrinter later in execution. I've simply added an exception with a more explicit message, and the test checks if it is raised

2024-11-14 00:16 UTC, sensslen commented
I created a PR on your repository with my suggested changes

2025-08-25 05:30 UTC, sensslen commented
Closing due to inactivity of the author and the PR getting out of sync with the repository

2025-08-25 05:30 UTC, closed without merging